repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest version
    hooks:
      - id: isort
        exclude: '\.(?!py$).*$'
  - repo: https://github.com/psf/black
    rev: 24.10.0  # Use the latest version
    hooks:
      - id: black
        exclude: '\.(?!py$).*$'